name: Deploy to Azure storage blob

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: npm install and zip code
        run: |
          npm ci
          zip -r ${{ github.event.repository.name }}.zip ./*

      - name: Upload to Azure
        run: |
          az storage blob upload -f ./billing-alert-function-app.zip \
          --sas-token ${{ secrets.SAS_TOKEN }} \
          -c billing-alert-function-releases \
          -n billing-alert-function-blob \
          --account-name stbillingalertfunc \
          --overwrite
